# Generated by Django 5.1 on 2024-08-23 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
